[package]
name = "camera_detection_bot"
version = "0.1.0"
edition = "2021"

[dependencies]
teloxide = { version = "0.13", features = ["macros"] }
log = "0.4"
pretty_env_logger = "0.5"
tokio = { version = "1.8", features = ["rt-multi-thread", "macros"] }
dotenv = "0.15.0"
warp = "0.3.7"
base64 = "0.22.1"
serde = "1.0.218"
futures = "0.3.31"
