
name: Generate & Deploy Python Docs

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest
    # добавляем src/ в PYTHONPATH для всех шагов
    env:
      PYTHONPATH: ${{ github.workspace }}/src

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install pdoc3
        run: pip install pdoc3

      - name: Generate docs with pdoc
        run: |
          rm -rf docs
          # теперь pdoc видит все ваши пакеты, 
          # т.к. src/ уже в PYTHONPATH
          pdoc --html src --output-dir docs --force

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
          publish_branch: gh-pages
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
