
name: Generate & Deploy Python Docs

permissions:
  contents: write
  pages: write

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest

    # делаем так, чтобы при import server, import database и т.п.
    # питон искал модули в папке src
    env:
      PYTHONPATH: ${{ github.workspace }}/src

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system deps for PySide6
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libegl-mesa0 \
            libgl1-mesa-dri \
            libgbm1 \
            libxkbcommon-x11-0 \
            libxcb-icccm4 \
            libxcb-image0 \
            libxcb-keysyms1 \
            libxcb-render0 \
            libxcb-render-util0 \
            libxcb-xinerama0

      - name: Install Python deps
        run: |
          pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pdoc3

      - name: Generate docs
        run: |
          rm -rf docs
          pdoc \
            --html \
            --force \
            --skip-errors \
            -o docs \
            bot \
            database \
            server \
            model \
            desktop \
            utils

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
          publish_branch: gh-pages
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
