name: Rust

on:
  push:
    branches: [ "telegram-bot" ]
  pull_request:
    branches: [ "telegram-bot" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run formatter
      run: cargo clippy --all-targets --all-features
    - name: Run tests
      run: cargo test --verbose
